### ISSUE TITLE
Cake.Core 0.26.0

### ISSUE THREAD

**Issue by wahmedswl** [cake-contrib/Cake.Http#47]
Hi, 
   Would it be possible to update to latest Cake.Core 0.26.0. Getting following error during build

```
rror: The assembly 'Cake.Http, Version=0.4.1.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.22.0). 
This assembly need to reference at least Cake.Core version 0.26.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

**Comment by gep13** [comment]
@wahmedswl as per the recommendation in the error message, there is a workaround which you can follow while waiting for this.

On top of this, we recommend that you ALWAYS pin to a specific version of Cake, so that you don't hit this type of issue.

You can find more information about this recommendation here:

https://cakebuild.net/docs/tutorials/pinning-cake-version
